[project]
name = "telegrag"
version = "0.1.0"
description = "Telegram RAG Bot"
requires-python = ">=3.11"
dependencies = [
    "fastapi",
    "uvicorn[standard]",
    "celery",
    "redis",
    "aiogram",
    "structlog",
    "pydantic-settings",
    "qdrant-client",
    "fastembed",
    "sqlmodel",
    "psycopg2-binary",
    "asyncpg",
    "sqlalchemy>=2.0.45",
    "google-genai",
    "pypdf",
    "python-dotenv",
    "httpx",
    "watchdog"
]